# Generated by Django 5.1 on 2024-08-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='photos')),
                ('telegram', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('profession', models.CharField(max_length=50)),
                ('bio', models.TextField()),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'ordering': ['id'],
            },
        ),
    ]
